@startuml
!include <C4/C4_Container>

Person(clients, "Clients", "Веб-приложение или мобильное приложение")
Person(help, "Support service", "Служба поддержки")
Person(sales, "Sales department", "Отдел продаж")
System_Boundary(c1, "Теплый дом") {
  System(apiGateway, "API Gateway", "Центральная точка входа для всех запросов\n REST API")
  System(authService, "Authentication Service", "Авторизация и аутентификация")
  System(automationService, "Automation Service", "Управляет сценариями и автоматизацией")
  System(configurationService, "Configuration Service", "Хранит конфигурации устройств и сценариев")
  System(telemetryService, "Telemetry Service", "Собирает и хранит данные с устройств")
  System(integrationService, "Integration Service", "Предоставляет API для работы с устройствами партнёров")
  System(helpService, "Knowledgebase Service", "База знаний")
  System(ticketService, "Ticket Service", "Тикет система для работы с проблемами от клиентов")
  System(notificationService, "Notification Service", "Отправляет уведомления пользователям через различные каналы")
  System(analyticsService, "Analytics Service", "Сервис аналитики")
  System(orderService, "Order Service", "Сервис заказов")
  System(billingService, "Billing Service", "Сервис оплат")
  System(aclService, "ACL Service", "Anti-Corruption Layer сервис")
  System(monolith, "software system", "монолит компании Теплый дом, Java")
}

System_Ext(devices, "Устройства умного дома")
System_Ext(fcm, "Firebase Cloud Messaging")
System_Ext(email, "Email")
System_Ext(sms, "SMS")
System_Ext(extPaymentProviders, "Payment providers")

Rel(clients, apiGateway, "","", "Запросы контента через браузер или мобильное приложение")
Rel(help, apiGateway, "","", "Запросы контента через браузер")
Rel(sales, apiGateway, "", "", "Запросы контента через браузер")
Rel(apiGateway, authService, "", "", "Запросы на авторизацию и аутентификацию")
Rel(configurationService, automationService, "", "Создание и редактирование сценариев")
Rel(automationService, integrationService, "", "","Запускает сценарии по событиям или расписанию")
Rel(apiGateway, telemetryService, "", "", "Запросы на получение телеметрии")
Rel(apiGateway, configurationService, "", "","Запросы на создание и редактирование сценариев и автоматизацию")
Rel(apiGateway, notificationService, "", "", "Запросы на получение отправленных уведомлений")
Rel(apiGateway, helpService, "", "", "Запросы на получение из базы знаний")
Rel(apiGateway, ticketService, "", "", "Запросы на получение и создание тикетов")
Rel(apiGateway, analyticsService, "", "", "Запросы на получение и создание отчетов")
Rel(apiGateway, orderService, "", "", "Запросы на для работы с заказами")
Rel(apiGateway, billingService, "", "", "Запросы для работы с оплатами")
Rel(billingService, extPaymentProviders, "", "", "Запросы для работы с оплатами")
Rel(orderService, billingService, "", "", "Запросы для работы с оплатами")
Rel(configurationService, integrationService, "", "", "Передача конфигурации")
Rel(telemetryService, integrationService, "", "", "Собирает телеметрию с утройств")
Rel(integrationService, devices, "", "", "Взаимодействие с партнерскими устройствами")
Rel(notificationService, fcm, "", "", "Отправка пушей")
Rel(notificationService, email, "", "", "Отправка писем")
Rel(notificationService, sms, "", "", "Отправка СМС")
Rel(apiGateway, aclService, "", "", "Запросы на к acl")
Rel(aclService, monolith, "", "", "Запросы на к текущему сервису")

@enduml
